# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes m ade in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(628, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(628, 395))
        MainWindow.setMaximumSize(QtCore.QSize(628, 395))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setContentsMargins(10, 10, 20, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelPixTypeEtiquette = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPixTypeEtiquette.sizePolicy().hasHeightForWidth())
        self.labelPixTypeEtiquette.setSizePolicy(sizePolicy)
        self.labelPixTypeEtiquette.setMaximumSize(QtCore.QSize(24, 24))
        self.labelPixTypeEtiquette.setText("")
        self.labelPixTypeEtiquette.setPixmap(QtGui.QPixmap(":/custom-icons/barcode-qr.svg"))
        self.labelPixTypeEtiquette.setScaledContents(True)
        self.labelPixTypeEtiquette.setObjectName("labelPixTypeEtiquette")
        self.horizontalLayout.addWidget(self.labelPixTypeEtiquette)
        self.labelTypeEtiquette = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTypeEtiquette.sizePolicy().hasHeightForWidth())
        self.labelTypeEtiquette.setSizePolicy(sizePolicy)
        self.labelTypeEtiquette.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTypeEtiquette.setObjectName("labelTypeEtiquette")
        self.horizontalLayout.addWidget(self.labelTypeEtiquette)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.comboBoxTypeEtiquette = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxTypeEtiquette.setObjectName("comboBoxTypeEtiquette")
        self.verticalLayout_3.addWidget(self.comboBoxTypeEtiquette)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelPixOperateur = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPixOperateur.sizePolicy().hasHeightForWidth())
        self.labelPixOperateur.setSizePolicy(sizePolicy)
        self.labelPixOperateur.setMaximumSize(QtCore.QSize(24, 24))
        self.labelPixOperateur.setText("")
        self.labelPixOperateur.setPixmap(QtGui.QPixmap(":/custom-icons/single-01.svg"))
        self.labelPixOperateur.setScaledContents(True)
        self.labelPixOperateur.setObjectName("labelPixOperateur")
        self.horizontalLayout_3.addWidget(self.labelPixOperateur)
        self.labelOperateur = QtWidgets.QLabel(self.centralwidget)
        self.labelOperateur.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOperateur.setObjectName("labelOperateur")
        self.horizontalLayout_3.addWidget(self.labelOperateur)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.comboBoxOperateur = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxOperateur.setObjectName("comboBoxOperateur")
        self.verticalLayout_3.addWidget(self.comboBoxOperateur)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelPixDate = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPixDate.sizePolicy().hasHeightForWidth())
        self.labelPixDate.setSizePolicy(sizePolicy)
        self.labelPixDate.setMaximumSize(QtCore.QSize(24, 24))
        self.labelPixDate.setText("")
        self.labelPixDate.setPixmap(QtGui.QPixmap(":/custom-icons/calendar-60.svg"))
        self.labelPixDate.setScaledContents(True)
        self.labelPixDate.setObjectName("labelPixDate")
        self.horizontalLayout_4.addWidget(self.labelPixDate)
        self.labelDate = QtWidgets.QLabel(self.centralwidget)
        self.labelDate.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDate.setObjectName("labelDate")
        self.horizontalLayout_4.addWidget(self.labelDate)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.dateEditJour = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEditJour.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEditJour.setObjectName("dateEditJour")
        self.verticalLayout_3.addWidget(self.dateEditJour)
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.pushBoutonSaisie = QtWidgets.QPushButton(self.centralwidget)
        self.pushBoutonSaisie.setMinimumSize(QtCore.QSize(0, 40))
        self.pushBoutonSaisie.setObjectName("pushBoutonSaisie")
        self.verticalLayout_3.addWidget(self.pushBoutonSaisie)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setContentsMargins(20, 10, 10, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelNumeroOf = QtWidgets.QLabel(self.centralwidget)
        self.labelNumeroOf.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNumeroOf.setObjectName("labelNumeroOf")
        self.verticalLayout_2.addWidget(self.labelNumeroOf)
        self.lineEditNumeroOf = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNumeroOf.setObjectName("lineEditNumeroOf")
        self.verticalLayout_2.addWidget(self.lineEditNumeroOf)
        self.labelReferenceProduit = QtWidgets.QLabel(self.centralwidget)
        self.labelReferenceProduit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelReferenceProduit.setObjectName("labelReferenceProduit")
        self.verticalLayout_2.addWidget(self.labelReferenceProduit)
        self.lineEditRefProduit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditRefProduit.setObjectName("lineEditRefProduit")
        self.verticalLayout_2.addWidget(self.lineEditRefProduit)
        self.labelQuantite = QtWidgets.QLabel(self.centralwidget)
        self.labelQuantite.setAlignment(QtCore.Qt.AlignCenter)
        self.labelQuantite.setObjectName("labelQuantite")
        self.verticalLayout_2.addWidget(self.labelQuantite)
        self.lineEditQuantite = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditQuantite.setObjectName("lineEditQuantite")
        self.verticalLayout_2.addWidget(self.lineEditQuantite)
        self.labelNumeroSerie = QtWidgets.QLabel(self.centralwidget)
        self.labelNumeroSerie.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNumeroSerie.setObjectName("labelNumeroSerie")
        self.verticalLayout_2.addWidget(self.labelNumeroSerie)
        self.lineEditNumeroSerie = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNumeroSerie.setObjectName("lineEditNumeroSerie")
        self.verticalLayout_2.addWidget(self.lineEditNumeroSerie)
        self.labelVersion = QtWidgets.QLabel(self.centralwidget)
        self.labelVersion.setAlignment(QtCore.Qt.AlignCenter)
        self.labelVersion.setObjectName("labelVersion")
        self.verticalLayout_2.addWidget(self.labelVersion)
        self.lineEditVersion = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditVersion.setObjectName("lineEditVersion")
        self.verticalLayout_2.addWidget(self.lineEditVersion)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBar.setMovable(False)
        self.toolBar.setOrientation(QtCore.Qt.Vertical)
        self.toolBar.setIconSize(QtCore.QSize(36, 36))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionConfig = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/custom-icons/settings-gear-63.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfig.setIcon(icon)
        self.actionConfig.setText("")
        self.actionConfig.setObjectName("actionConfig")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/custom-icons/edit-redo-rtl.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon1)
        self.actionUndo.setText("")
        self.actionUndo.setObjectName("actionUndo")
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/custom-icons/system-shutdown-symbolic.symbolic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuitter.setIcon(icon2)
        self.actionQuitter.setText("")
        self.actionQuitter.setIconVisibleInMenu(True)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/custom-icons/system-search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/custom-icons/multiple-11.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionInfo.setIcon(icon3)
        self.actionInfo.setText("")
        self.actionInfo.setObjectName("actionInfo")
        self.actionSpacer = QtWidgets.QAction(MainWindow)
        self.actionSpacer.setEnabled(False)
        self.actionSpacer.setText("")
        self.actionSpacer.setIconText("")
        font = QtGui.QFont()
        self.actionSpacer.setFont(font)
        self.actionSpacer.setVisible(True)
        self.actionSpacer.setObjectName("actionSpacer")
        self.actionUnitaire = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/custom-icons/barcode-qr.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionUnitaire.setIcon(icon4)
        self.actionUnitaire.setText("")
        self.actionUnitaire.setObjectName("actionUnitaire")
        self.toolBar.addAction(self.actionConfig)
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionInfo)
        self.toolBar.addAction(self.actionUnitaire)
        self.toolBar.addAction(self.actionSpacer)
        self.toolBar.addAction(self.actionQuitter)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Logiciel Impression Etiquettes"))
        self.labelTypeEtiquette.setText(_translate("MainWindow", "Type Etiquette"))
        self.labelOperateur.setText(_translate("MainWindow", "Opérateur"))
        self.labelDate.setText(_translate("MainWindow", "Date"))
        self.pushBoutonSaisie.setText(_translate("MainWindow", "Lancer la saisie"))
        self.labelNumeroOf.setText(_translate("MainWindow", "Numéro OF (OF)"))
        self.labelReferenceProduit.setText(_translate("MainWindow", "Référence Produit (RP)"))
        self.labelQuantite.setText(_translate("MainWindow", "Quantité (Q)"))
        self.labelNumeroSerie.setText(_translate("MainWindow", "Numéro de Série (NS)"))
        self.labelVersion.setText(_translate("MainWindow", "Version (V)"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionConfig.setToolTip(_translate("MainWindow", "Configuration d\'impression"))
        self.actionUndo.setToolTip(_translate("MainWindow", "Recommencer la saisie"))
        self.actionQuitter.setToolTip(_translate("MainWindow", "Quitter l\'application"))
        self.actionInfo.setToolTip(_translate("MainWindow", "Info sur le logiciel"))
        self.actionUnitaire.setToolTip(_translate("MainWindow", "Impression unitaire"))

import imprimeti.qt.icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

