# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setupwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SetUpWindow(object):
    def setupUi(self, SetUpWindow):
        SetUpWindow.setObjectName("SetUpWindow")
        SetUpWindow.resize(533, 500)
        self.centralwidget = QtWidgets.QWidget(SetUpWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, -1, -1, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelOutFilename = QtWidgets.QLabel(self.centralwidget)
        self.labelOutFilename.setObjectName("labelOutFilename")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelOutFilename)
        self.lineEditOutFilename = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditOutFilename.setObjectName("lineEditOutFilename")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditOutFilename)
        self.labelDevice = QtWidgets.QLabel(self.centralwidget)
        self.labelDevice.setObjectName("labelDevice")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelDevice)
        self.lineEditDeviceName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDeviceName.setObjectName("lineEditDeviceName")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditDeviceName)
        self.verticalLayout.addLayout(self.formLayout)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lineEditHostName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditHostName.setObjectName("lineEditHostName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditHostName)
        self.labelHostName = QtWidgets.QLabel(self.centralwidget)
        self.labelHostName.setObjectName("labelHostName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelHostName)
        self.labelUserName = QtWidgets.QLabel(self.centralwidget)
        self.labelUserName.setObjectName("labelUserName")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelUserName)
        self.labelPassword = QtWidgets.QLabel(self.centralwidget)
        self.labelPassword.setObjectName("labelPassword")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelPassword)
        self.lineEditUserName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditUserName)
        self.lineEditPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditPassword)
        self.labelDatabaseName = QtWidgets.QLabel(self.centralwidget)
        self.labelDatabaseName.setObjectName("labelDatabaseName")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelDatabaseName)
        self.lineEditDatabaseName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDatabaseName.setObjectName("lineEditDatabaseName")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditDatabaseName)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, 0, 10, 20)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.labelImage = QtWidgets.QLabel(self.centralwidget)
        self.labelImage.setText("")
        self.labelImage.setPixmap(QtGui.QPixmap(":/custom-icons/offsets2.png"))
        self.labelImage.setObjectName("labelImage")
        self.gridLayout.addWidget(self.labelImage, 1, 1, 1, 1)
        self.doubleSpinBoxXOffset = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxXOffset.setMinimumSize(QtCore.QSize(150, 0))
        self.doubleSpinBoxXOffset.setDecimals(1)
        self.doubleSpinBoxXOffset.setSingleStep(0.1)
        self.doubleSpinBoxXOffset.setObjectName("doubleSpinBoxXOffset")
        self.gridLayout.addWidget(self.doubleSpinBoxXOffset, 1, 0, 1, 1)
        self.doubleSpinBoxStepLabel = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxStepLabel.setSingleStep(0.01)
        self.doubleSpinBoxStepLabel.setObjectName("doubleSpinBoxStepLabel")
        self.gridLayout.addWidget(self.doubleSpinBoxStepLabel, 0, 1, 1, 1)
        self.doubleSpinBoxYOffset = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBoxYOffset.setDecimals(1)
        self.doubleSpinBoxYOffset.setSingleStep(0.1)
        self.doubleSpinBoxYOffset.setObjectName("doubleSpinBoxYOffset")
        self.gridLayout.addWidget(self.doubleSpinBoxYOffset, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonApply = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonApply.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButtonApply.setObjectName("pushButtonApply")
        self.horizontalLayout.addWidget(self.pushButtonApply)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButtonCancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCancel.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        SetUpWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SetUpWindow)
        QtCore.QMetaObject.connectSlotsByName(SetUpWindow)

    def retranslateUi(self, SetUpWindow):
        _translate = QtCore.QCoreApplication.translate
        SetUpWindow.setWindowTitle(_translate("SetUpWindow", "Configuration"))
        self.label.setText(_translate("SetUpWindow", "Paramètres de l\'application"))
        self.labelOutFilename.setText(_translate("SetUpWindow", "Fichier de sortie :"))
        self.labelDevice.setText(_translate("SetUpWindow", "Port de l\'imprimante :"))
        self.label_3.setText(_translate("SetUpWindow", "Accès base de donnée MariaDB"))
        self.labelHostName.setText(_translate("SetUpWindow", "Adresse"))
        self.labelUserName.setText(_translate("SetUpWindow", "Utilisateur"))
        self.labelPassword.setText(_translate("SetUpWindow", "Password"))
        self.labelDatabaseName.setText(_translate("SetUpWindow", "Nom de la Base"))
        self.label_2.setText(_translate("SetUpWindow", "Mise en page"))
        self.doubleSpinBoxXOffset.setSuffix(_translate("SetUpWindow", " mm"))
        self.doubleSpinBoxStepLabel.setSuffix(_translate("SetUpWindow", " mm"))
        self.doubleSpinBoxYOffset.setSuffix(_translate("SetUpWindow", " mm"))
        self.pushButtonApply.setText(_translate("SetUpWindow", "Appliquer"))
        self.pushButtonCancel.setText(_translate("SetUpWindow", "Fermer"))

import imprimeti.qt.icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SetUpWindow = QtWidgets.QMainWindow()
    ui = Ui_SetUpWindow()
    ui.setupUi(SetUpWindow)
    SetUpWindow.show()
    sys.exit(app.exec_())

